#pragma once

// 网页头部HTML
static const char *ROOT_HTML_1 =
    "<!DOCTYPE html>"
    "<html>"
    "<head>"
    "<meta charset=\"UTF-8\">"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    "<title>WiFi配置</title>"
    "<style>"
    "body {"
    "    font-family: 'Microsoft YaHei', sans-serif;"
    "    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    "    margin: 0;"
    "    padding: 0;"
    "    display: flex;"
    "    justify-content: center;"
    "    align-items: center;"
    "    min-height: 100vh;"
    "}"
    ".login-card {"
    "    background: rgba(255, 255, 255, 0.95);"
    "    padding: 40px;"
    "    border-radius: 20px;"
    "    box-shadow: 0 15px 35px rgba(0, 0, 0, 0.2);"
    "    width: 90%;"
    "    max-width: 400px;"
    "    backdrop-filter: blur(10px);"
    "}"
    ".login-card h1 {"
    "    text-align: center;"
    "    color: #333;"
    "    margin-bottom: 30px;"
    "    font-weight: 300;"
    "}"
    ".login-card h1 span {"
    "    color: #764ba2;"
    "    font-weight: 600;"
    "}"
    ".form-group {"
    "    margin-bottom: 20px;"
    "}"
    ".form-group label {"
    "    display: block;"
    "    margin-bottom: 8px;"
    "    color: #555;"
    "    font-weight: 500;"
    "}"
    ".form-control {"
    "    width: 100%;"
    "    padding: 12px 15px;"
    "    border: 2px solid #e1e1e1;"
    "    border-radius: 10px;"
    "    font-size: 16px;"
    "    transition: all 0.3s;"
    "    box-sizing: border-box;"
    "}"
    ".form-control:focus {"
    "    border-color: #764ba2;"
    "    outline: none;"
    "    box-shadow: 0 0 0 3px rgba(118, 75, 162, 0.1);"
    "}"
    ".btn {"
    "    width: 100%;"
    "    padding: 14px;"
    "    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    "    color: white;"
    "    border: none;"
    "    border-radius: 10px;"
    "    font-size: 16px;"
    "    font-weight: 600;"
    "    cursor: pointer;"
    "    transition: all 0.3s;"
    "}"
    ".btn:hover {"
    "    transform: translateY(-2px);"
    "    box-shadow: 0 7px 14px rgba(0, 0, 0, 0.1);"
    "}"
    ".btn:disabled {"
    "    opacity: 0.6;"
    "    cursor: not-allowed;"
    "    transform: none;"
    "}"
    ".scan-list {"
    "    margin-top: 5px;"
    "    font-size: 14px;"
    "    color: #666;"
    "}"
    ".status {"
    "    text-align: center;"
    "    margin-top: 20px;"
    "    padding: 10px;"
    "    border-radius: 8px;"
    "    font-size: 14px;"
    "}"
    ".status.success {"
    "    background-color: #d4edda;"
    "    color: #155724;"
    "}"
    ".status.error {"
    "    background-color: #f8d7da;"
    "    color: #721c24;"
    "}"
    "</style>"
    "</head>"
    "<body>"
    "<div class=\"login-card\">"
    "    <h1><span>登录</span><br>WiFi配置</h1>"
    "    <form method=\"POST\" action=\"/config\" enctype=\"application/x-www-form-urlencoded\">"
    "        <div class=\"form-group\">"
    "            <label for=\"ssid\">WiFi名称</label>"
    "            <input type=\"text\" id=\"ssid\" name=\"ssid\" class=\"form-control\" "
    "                   placeholder=\"请输入WiFi名称\" required list=\"wifi-list\">"
    "            <datalist id=\"wifi-list\">";

// 扫描到的WiFi列表会动态插入到这里

static const char *ROOT_HTML_2 =
    "            </datalist>"
    "        </div>"
    "        <div class=\"form-group\">"
    "            <label for=\"password\">WiFi密码</label>"
    "            <input type=\"password\" id=\"password\" name=\"password\" "
    "                   class=\"form-control\" placeholder=\"请输入WiFi密码\">"
    "        </div>"
    "        <button type=\"submit\" class=\"btn\">连接到WiFi</button>"
    "    </form>"
    "    <div class=\"status\" id=\"status\"></div>"
    "</div>"
    "<script>"
    "document.querySelector('form').addEventListener('submit', function(e) {"
    "    e.preventDefault();"
    "    "
    "    // 手动构建URL编码的表单数据"
    "    var formData = new URLSearchParams();"
    "    var ssid = document.getElementById('ssid').value;"
    "    var password = document.getElementById('password').value;"
    "    "
    "    if (!ssid || ssid.trim() === '') {"
    "        alert('请输入WiFi名称');"
    "        return;"
    "    }"
    "    "
    "    formData.append('ssid', ssid);"
    "    formData.append('password', password);"
    "    "
    "    fetch('/config', {"
    "        method: 'POST',"
    "        headers: {"
    "            'Content-Type': 'application/x-www-form-urlencoded'"
    "        },"
    "        body: formData.toString()"
    "    })"
    "    .then(response => {"
    "        if (!response.ok) {"
    "            throw new Error('网络响应错误: ' + response.status);"
    "        }"
    "        return response.text();"
    "    })"
    "    .then(data => {"
    "        document.getElementById('status').innerHTML = data;"
    "        document.getElementById('status').className = 'status success';"
    "        setTimeout(() => {"
    "            document.getElementById('status').innerHTML = '配置成功！3秒后设备将重启...';"
    "            setTimeout(() => { location.reload(); }, 3000);"
    "        }, 1000);"
    "    })"
    "    .catch(error => {"
    "        console.error('错误:', error);"
    "        document.getElementById('status').innerHTML = '配置失败: ' + error.message;"
    "        document.getElementById('status').className = 'status error';"
    "    });"
    "});"
    "</script>"
    "</body>"
    "</html>";